# Generated by Django 3.2.7 on 2022-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='position',
            field=models.IntegerField(null=True, unique=True, verbose_name='موقعیت'),
        ),
    ]
