# Generated by Django 3.2.7 on 2022-03-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_alter_faqquestion_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqquestion',
            old_name='title',
            new_name='question',
        ),
    ]
