# Generated by Django 3.1.3 on 2022-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_rename_title_faqquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
