# Generated by Django 3.2.7 on 2022-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='محتوا')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
            ],
            options={
                'verbose_name': 'محتوا',
                'verbose_name_plural': 'محتوا',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='زمان آپدیت')),
            ],
            options={
                'verbose_name': 'ایمیل',
                'verbose_name_plural': 'ایمیل\u200cها',
                'ordering': ('email',),
            },
        ),
    ]
