# Generated by Django 3.2.7 on 2022-04-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='longitude', verbose_name='آدرس محل'),
        ),
    ]
