# Generated by Django 3.2.7 on 2022-04-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_map_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='map',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان\u200c آپدیت'),
        ),
    ]
